#!/usr/bin/sh
#
# Kernel hook for rEFInd.
#
# Arguments passed to this script: $1 pkgname, $2 version.
#
PKGNAME="$1"
VERSION="$2"
cp /boot/vmlinuz-${VERSION} /boot/efi
cp /boot/initramfs-${VERSION}.img /boot/efi
