#!/bin/sh

# Start in a current directory
file="${PWD}"

while true; do
    # Call wofi
    file="$(ls -ap | wofi -d -p $PWD -k /dev/null)"
    # Exit if nothing selected
    if [ "${file}" = "" ]; then exit; fi
    # If a file is selected, open it
    if [ -f "${file}" ]; then xdg-open "${file}"; exit; fi
    # And if directory is selected, cd to it
    cd "${file}"
done
