#!/bin/sh
action="$(echo -e "shutdown (1)\nreboot (2)\nlock (3)" | wofi -d -p "Power menu" -k /dev/null)"
case $action in
    shutdown*)
        doas -n shutdown now
        ;;
    reboot*)
        doas -n reboot
        ;;
    lock*)
        swaymsg exec \$locker
        ;;
    *)
        exit 1
        ;;
esac
